on:
  push:
    branches: [main]

jobs:
  reefer:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno cache src/main.ts

      - name: Run
        run: deno run --allow-net --allow-read --allow-env --allow-ffi src/main.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          TRACKING_ISSUE_NO: 1
